'use client';

import { useMemo, useState } from 'react';
import { AlertCircle, ArrowLeft, ArrowRight, ArrowUpRight, BookOpen, CheckCircle2, ClipboardCheck, Clock3, Download, ExternalLink, FileSearch, GraduationCap, Layers3, Library, Route, Search, ShieldCheck, Target, TimerReset } from 'lucide-react';
import { SidebarProvider, Sidebar, SidebarContent, SidebarFooter, SidebarHeader, SidebarMenu, SidebarMenuButton, SidebarMenuItem, SidebarTrigger } from '@/components/ui/sidebar';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Progress } from '@/components/ui/progress';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { Checkbox } from '@/components/ui/checkbox';
import { capstoneTasks, getPlan, intensiveWeeks, lessonExtras, lessons, sourceBank, stages, taskLabs, trackNames, type Lesson, type Track } from '@/lib/course';
import sources from '@/lib/sources.json';
import regulations from '@/lib/regulations.json';

const nav=[{label:'总控台',icon:Target},{label:'章节精讲',icon:BookOpen},{label:'高压计划',icon:Route},{label:'模拟考场',icon:ClipboardCheck},{label:'资料库',icon:Library}];

function download(name:string,text:string){const url=URL.createObjectURL(new Blob(['\ufeff'+text],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),700);}
function Heading({tag,title,body,stamp}:{tag:string;title:string;body:string;stamp?:string}){return <div className="page-heading"><div><p className="eyebrow">{tag}</p><h1>{title}</h1><p>{body}</p></div>{stamp?<span className="course-label">{stamp}</span>:null}</div>}
function Sources({ids}:{ids:string[]}){return <div className="source-chain">{ids.map(id=>{const item=sourceBank.find(x=>x.id===id);return item?<a href={item.url} key={id} target="_blank" rel="noreferrer">{item.authority} · {item.title}<ExternalLink size={13}/></a>:null;})}</div>}
function RegulationLibrary({query,tab,setTab}:{query:string;tab:string;setTab:(tab:string)=>void}){const labels={national:'国家政策法规',anhui:'安徽省政策法规',suzhou:'宿州本地政策法规'} as const;const selected=tab in labels?tab:'national';const items=regulations.filter(x=>x.category===selected&&(x.title+x.status+x.categoryName).includes(query.trim()));return <><Heading tag="REGULATION LIBRARY" title="国家、安徽与宿州政策资料库" body="本站已保存平台可抓取的网页文本，并始终保留原文入口。文本是学习检索副本；项目办理时应核对发布机关、现行效力、条款与附件。" stamp={'86条目录 · '+regulations.filter(x=>x.localTextUrl).length+'份站内文本'}/><div className="research-note"><FileSearch size={22}/><p>本次已抓取国家政策法规 40 条、安徽省政策法规 13 条、宿州本地政策法规 33 条。正文较短的页面通常需要继续打开原页或附件核对，不会被当作完整现行规则。</p></div><div className="library-toolbar"><Tabs value={selected} onValueChange={setTab}><TabsList className="path-tabs training-tabs regulation-tabs"><TabsTrigger value="national">国家（40）</TabsTrigger><TabsTrigger value="anhui">安徽（13）</TabsTrigger><TabsTrigger value="suzhou">宿州（33）</TabsTrigger></TabsList></Tabs></div><div className="notice"><AlertCircle size={19}/><p>每条资料都提供“站内文本”和“平台原页”。站内文本便于学习与检索；原页用于核对附件、文号、有效状态和更新情况。</p></div><div className="policy-list">{items.map(x=><article className="policy-row" key={x.id}><div><span className="type-label">{x.categoryName}</span><h3>{x.title}</h3><p>{x.status}</p><small>{x.characters?x.characters.toLocaleString()+' 字符 · ':''}抓取于 {x.retrieved}</small></div><div className="policy-actions">{x.localTextUrl?<a href={x.localTextUrl} target="_blank" rel="noreferrer">站内文本 <FileSearch size={15}/></a>:null}<a href={x.url} target="_blank" rel="noreferrer">平台原页 <ExternalLink size={15}/></a></div></article>)}</div>{!items.length?<p className="empty">没有匹配资料，请更换关键词或切换分类。</p>:null}</>}

function LessonScreen({lesson,answers,setAnswers,practice,setPractice,submissions,setSubmissions,submitted,passed,onSubmit,onBack}:{lesson:Lesson;answers:Record<string,number>;setAnswers:(x:Record<string,number>)=>void;practice:Record<string,boolean[]>;setPractice:(x:Record<string,boolean[]>)=>void;submissions:Record<string,Record<string,string>>;setSubmissions:(x:Record<string,Record<string,string>>)=>void;submitted:Record<string,boolean>;passed:string[];onSubmit:()=>void;onBack:()=>void}){
 const extra=lessonExtras[lesson.id]; const lab=taskLabs[lesson.id]; const work=practice[lesson.id]||Array(lab.steps.length).fill(false); const form=submissions[lesson.id]||{};
 return <><button className="back-button" onClick={onBack}><ArrowLeft size={16}/> 返回章节目录</button><Heading tag={trackNames[lesson.track]+' · 第'+lesson.week+'周 · '+lesson.id.toUpperCase()} title={lesson.title} body={lesson.summary} stamp={'建议 '+lesson.hours+' 小时 · '+lesson.questions.length+'题闭卷卷'}/>
 <div className="lesson-layout"><section className="lesson-content">
  <div className="teacher-opening"><GraduationCap size={26}/><div><b>本章结束时必须掌握的能力</b><p>{lesson.goal}</p></div></div>
  <div className="teacher-scene"><p className="eyebrow">老师先带你进入场景</p><h2>你会遇到什么</h2><p>{extra.scene}</p><div><b>老师示范怎么想</b><p>{extra.example}</p></div></div>
  <section className="knowledge-section"><p className="eyebrow">第一部分 · 核心讲义</p><h2>五个重点，逐点讲清“懂什么、怎么做、如何留证”</h2>
   {lesson.knowledge.map((point,i)=>{const step=lab.steps[i%lab.steps.length];const source=sourceBank.find(x=>x.id===lesson.sourceIds[i%lesson.sourceIds.length]);return <article className="knowledge-card detailed-card" key={point.title}><span>{String(i+1).padStart(2,'0')}</span><div><h3>{point.title}</h3><div className="teaching-grid"><p><b>先听懂</b>{point.detail}</p><p><b>现场如何判断</b>{extra.scene}</p><p><b>手上如何做</b>{step.instruction}</p><p><b>留下什么证据</b>{step.evidence}</p></div><div className="point-source"><FileSearch size={14}/>本节核对：{source?.authority}《{source?.title}》</div></div></article>})}
  </section>
  <section className="memory-box"><p className="eyebrow">第二部分 · 记忆与纠错</p><h2>本章必须记牢</h2><ul>{lesson.memory.map(x=><li key={x}>{x}</li>)}</ul></section>
  <section className="mistake-box"><p className="eyebrow">第三部分 · 初学者误区</p><h2>老师提前替你踩坑</h2>{extra.mistakes.map((x,i)=><p key={x}><b>{i+1}.</b>{x}</p>)}</section>
  <section className="practice-lab task-lab"><p className="eyebrow">第四部分 · 本章实训工单</p><h2>不是“写感想”，而是完成一份能交给老师检查的工作成果</h2><div className="task-brief"><b>训练情景</b><p>{lab.brief}</p></div><div className="task-materials"><b>开始前准备的材料</b><ul>{lab.materials.map(x=><li key={x}>{x}</li>)}</ul></div>
   <div className="task-steps">{lab.steps.map((step,i)=><label className="practice-step detailed-step" key={step.title}><Checkbox checked={work[i]} onCheckedChange={v=>{const copy=[...work];copy[i]=v===true;setPractice({...practice,[lesson.id]:copy});}}/><span><b>步骤 {i+1} · {step.title}</b><em>具体做法：{step.instruction}</em><small>完成凭证：{step.evidence}</small></span></label>)}</div>
   <div className="deliverable-template"><p className="eyebrow">交付模板</p><h3>{lesson.deliverable}</h3><p>按以下四栏填写。系统不再用“写满100字”判断作业；老师要检查的是事实、依据、判断和下一步是否完整。</p>{lab.template.map(field=><label key={field.label}><b>{field.label}</b><span>{field.prompt}</span><textarea value={form[field.label]||''} onChange={e=>setSubmissions({...submissions,[lesson.id]:{...form,[field.label]:e.target.value}})} rows={4} placeholder={field.prompt}/></label>)}</div>
   <div className="acceptance"><b>老师验收时看什么</b><ul>{lab.criteria.map(x=><li key={x}>{x}</li>)}</ul><p><strong>合格示例：</strong>{lab.model}</p></div>
  </section>
  <section className="quiz"><p className="eyebrow">第五部分 · 闭卷检查</p><h2>10题覆盖五个重点、交付标准与依据定位</h2><p className="quiz-intro">先独立答题，再提交查看解析。五道“重点题”分别对应上方五个核心讲义，不能只靠记住三道题过关。</p>{lesson.questions.map((item,i)=>{const key=lesson.id+'-'+i;return <div className="quiz-question" key={item.prompt}><b>第 {i+1} 题 / {lesson.questions.length}</b><p>{item.prompt}</p><RadioGroup value={answers[key]===undefined?'':String(answers[key])} onValueChange={v=>setAnswers({...answers,[key]:Number(v)})} aria-label={item.prompt}>{item.options.map((o,j)=><label className="answer-option" htmlFor={key+'-'+j} key={o}><RadioGroupItem id={key+'-'+j} value={String(j)}/><span>{o}</span></label>)}</RadioGroup>{submitted[lesson.id]?<div className={'mini-feedback '+(answers[key]===item.correct?'correct':'incorrect')}><strong>{answers[key]===item.correct?'正确':'回到对应重点复习'}</strong><span>{item.explanation}</span></div>:null}</div>})}
   <button className="primary" disabled={!lesson.questions.every((_,i)=>answers[lesson.id+'-'+i]!==undefined)} onClick={onSubmit}>提交本章闭卷与作业检查 <ArrowRight size={16}/></button>{submitted[lesson.id]?<div className={'feedback '+(passed.includes(lesson.id)?'correct':'incorrect')}><strong>{passed.includes(lesson.id)?'已达到在线自检门槛':'还不能通过本章'}</strong><p>{passed.includes(lesson.id)?'请导出四栏交付与答题解析，交导师复核。':'需要完成四个实训步骤、四栏交付模板，并将10道题全部答对。'}</p></div>:null}
  </section>
 </section><aside className="lesson-aside"><div className="panel ability-panel"><p className="eyebrow">ABILITY TARGET</p><h3>学完要会什么</h3><ul>{extra.ability.map(x=><li key={x}>{x}</li>)}</ul></div><div className="panel"><p className="eyebrow">SOURCE CHAIN</p><h3>本章依据</h3><p>每个重点卡都已分配本章应回查的来源；实际项目要继续定位到适用条款与当前版本。</p><Sources ids={lesson.sourceIds}/></div><div className="panel warning-panel"><TimerReset size={20}/><h3>本章硬门槛</h3><p>{lesson.gate}</p></div></aside></div></>
}

export default function Home(){
 const [view,setView]=useState('总控台'); const [track,setTrack]=useState<Track>('common'); const [lessonId,setLessonId]=useState<string|null>(null); const [answers,setAnswers]=useState<Record<string,number>>({}); const [practice,setPractice]=useState<Record<string,boolean[]>>({}); const [submissions,setSubmissions]=useState<Record<string,Record<string,string>>>({}); const [submitted,setSubmitted]=useState<Record<string,boolean>>({}); const [passed,setPassed]=useState<string[]>([]); const [hours,setHours]=useState(12); const [query,setQuery]=useState(''); const [libraryTab,setLibraryTab]=useState('official'); const [examDraft,setExamDraft]=useState<Record<string,string>>({}); const [examMessage,setExamMessage]=useState('');
 const lesson=lessons.find(x=>x.id===lessonId); const plan=getPlan(hours); const next=lessons.find(x=>!passed.includes(x.id))||lessons[0]; const completed=(t:Track)=>lessons.filter(x=>x.track===t&&passed.includes(x.id)).length;
 const report=useMemo(()=>['# 标途 · 高强度训练记录','','总训练量：'+plan.total+'小时；每周：'+plan.hours+'小时；预计：'+plan.weeks+'周。','章节通过：'+passed.length+'/'+lessons.length,'',...lessons.flatMap(x=>['## '+x.id.toUpperCase()+' '+x.title,'状态：'+(passed.includes(x.id)?'达到在线自检门槛':'未通过或未完成'),...taskLabs[x.id].template.flatMap(field=>[field.label+'：'+(submissions[x.id]?.[field.label]||'未填写')]),'']), '## 综合压测',...capstoneTasks.flatMap(x=>['### '+x.title,examDraft[x.id]||'未填写','']),'## 导师复核说明','在线通过不代表独立项目授权。导师须另行复核交付质量、真实性、异常处置和真实项目跟岗。'].join('\n'),[plan,passed,submissions,examDraft]);
 function go(name:string){setView(name==='资料库'?'法规资料库':name);setLessonId(null);setExamMessage('');window.scrollTo({top:0,behavior:'smooth'});} function open(item:Lesson){setView('章节精讲');setLessonId(item.id);window.scrollTo({top:0,behavior:'smooth'});}
 function submitLesson(){if(!lesson)return;const lab=taskLabs[lesson.id];setSubmitted({...submitted,[lesson.id]:true});const checks=practice[lesson.id]||[];const stepsDone=checks.length===lab.steps.length&&checks.every(Boolean);const outputDone=lab.template.every(x=>(submissions[lesson.id]?.[x.label]||'').trim().length>=10);const allCorrect=lesson.questions.every((q,i)=>answers[lesson.id+'-'+i]===q.correct);if(stepsDone&&outputDone&&allCorrect)setPassed(x=>x.includes(lesson.id)?x:[...x,lesson.id]);}
 return <SidebarProvider><Sidebar className="app-sidebar"><SidebarHeader><div className="brand"><span className="brand-symbol"><Layers3 size={24}/></span><div>标途<span>招投标实战训练营</span></div></div></SidebarHeader><SidebarContent><div className="nav-label">20周 · 240小时</div><SidebarMenu>{nav.map(({label,icon:Icon})=><SidebarMenuItem key={label}><SidebarMenuButton isActive={view===label} onClick={()=>go(label)}><Icon/><span>{label}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarContent><SidebarFooter><div className="sidebar-note"><GraduationCap/><strong>以交付物证明能力</strong><p>讲义 · 实训工单 · 10题周测 · 错题回炉</p></div><button className="text-button" onClick={()=>download('标途-训练记录.md',report)}><Download size={16}/> 导出训练记录</button><small>当前为试用版，刷新前请导出。<br/>在线自检不等于获得项目授权。</small></SidebarFooter></Sidebar><div className="workspace"><header className="topbar"><div><SidebarTrigger/><span>训练营 / {view}{lesson?' / '+lesson.id.toUpperCase():''}</span></div><span className="edition">建设工程 · 招标组织＋投标实务</span></header><main className="main">
 {view==='总控台'&&!lesson&&<><Heading tag="INTENSIVE CAMP · DAY 01" title="把小白训练成能扛项目的人。" body="每一章都用完整讲义、实训工单和10题闭卷卷，把“知道”变成能交接、能复核的工作成果。" stamp="20周 · 240小时"/><div className="intensive-banner"><div><span className="intensity-mark">TODAY'S MISSION</span><h2>{next.id.toUpperCase()} · {next.title}</h2><p>{next.summary}</p><div className="mission-list"><span><Clock3 size={15}/>建议 {next.hours} 小时</span><span><ShieldCheck size={15}/> {next.gate}</span></div><button className="primary" onClick={()=>open(next)}>进入完整讲义 <ArrowRight size={17}/></button></div><div className="scoreboard"><span>在线自检通过</span><strong>{passed.length}<small> / 18章</small></strong><Progress value={passed.length/18*100}/><p>通过条件：四步实训、四栏交付、10道闭卷题全对。</p></div></div><div className="dashboard-grid"><section><div className="section-heading"><h2>全流程，两条线同步理解</h2><span>每个阶段都要知道自己该做什么、不该做什么</span></div><div className="process-grid">{stages.map((x,i)=><button className="process-item" key={x.title} onClick={()=>go('章节精讲')}><span>{String(i+1).padStart(2,'0')}</span><strong>{x.title}</strong><ArrowUpRight size={15}/></button>)}</div><div className="section-heading"><h2>三道关卡</h2><span>基础不过，不建议跳到专业线</span></div><div className="pressure-grid"><article><b>第一关</b><h3>公共基础 6章</h3><p>理解项目、制度、门槛、文件、节点和电子证据。</p><button onClick={()=>{setTrack('common');go('章节精讲')}}>进入基础课 <ArrowRight size={15}/></button></article><article><b>第二关</b><h3>招标组织 6章</h3><p>从需求、资格、文件到答疑、开评标和归档。</p><button onClick={()=>{setTrack('org');go('章节精讲')}}>进入组织线 <ArrowRight size={15}/></button></article><article><b>第三关</b><h3>投标实务 6章</h3><p>从决策、证据、响应到递交和履约交接。</p><button onClick={()=>{setTrack('bid');go('章节精讲')}}>进入投标线 <ArrowRight size={15}/></button></article></div></section><aside className="right-column"><div className="panel"><p className="eyebrow">EACH CHAPTER</p><h3>章节交付要求</h3><ul className="strict-list"><li>五个核心讲义 <b>逐点回查</b></li><li>实训工作步骤 <b>4步</b></li><li>结构化交付 <b>4栏</b></li><li>闭卷检查 <b>10题全对</b></li></ul></div><div className="panel tinted"><p className="eyebrow">CURRENT PROGRESS</p><h3>三线通过情况</h3>{(Object.keys(trackNames) as Track[]).map(t=><div className="track-progress" key={t}><span>{trackNames[t]}</span><b>{completed(t)} / 6</b></div>)}</div></aside></div></>}
 {view==='章节精讲'&&!lesson&&<><Heading tag="TEACHER-LED CHAPTERS" title="每一章都是完整讲义与实训工单。" body="每个核心点都明确概念、现场判断、操作动作、留痕证据和应回查的依据；作业不再是一句宽泛任务。" stamp={trackNames[track]+' · '+completed(track)+'/6通过'}/><Tabs value={track} onValueChange={v=>setTrack(v as Track)}><TabsList className="path-tabs training-tabs">{(Object.keys(trackNames) as Track[]).map(t=><TabsTrigger key={t} value={t}>{trackNames[t]}（{completed(t)}/6）</TabsTrigger>)}</TabsList></Tabs><div className="course-intro"><BookOpen size={22}/><p>{track==='common'?'零基础先建立术语、制度、文件和节点的共同地图。':'专业线从本岗位的真实任务出发，先读讲义，再完成带材料、步骤和验收标准的工单。'}</p></div><div className="chapter-grid">{lessons.filter(x=>x.track===track).map((item,i)=><article className={'chapter-card '+(passed.includes(item.id)?'chapter-done':'')} key={item.id}><div className="chapter-card-top"><span>第 {item.week} 周 · {item.id.toUpperCase()}</span>{passed.includes(item.id)?<CheckCircle2 size={18}/>:<Clock3 size={18}/>}</div><h2>{item.title}</h2><p>{item.summary}</p><div className="chapter-skills">{lessonExtras[item.id].ability.map(x=><span key={x}>{x}</span>)}</div><div className="chapter-card-foot"><small>5个重点 · 4步工单 · 10题闭卷</small><button className="secondary" onClick={()=>open(item)}>开始第 {i+1} 章 <ArrowRight size={15}/></button></div></article>)}</div></>}
 {view==='章节精讲'&&lesson&&<LessonScreen lesson={lesson} answers={answers} setAnswers={setAnswers} practice={practice} setPractice={setPractice} submissions={submissions} setSubmissions={setSubmissions} submitted={submitted} passed={passed} onSubmit={submitLesson} onBack={()=>setLessonId(null)}/>}
 {view==='高压计划'&&!lesson&&<><Heading tag="GAOKAO-STYLE RHYTHM" title="20周，不留“学过但不会”的空档。" body="默认每周12小时、每周6天训练。每周有可检查成果，80分以下补训，红线题必须满分。" stamp={plan.total+'小时 · 预计'+plan.weeks+'周'}/><div className="plan-banner intense-plan"><div><span className="pill light">压力来自清晰门槛，不来自盲目熬夜</span><h2>每周训练负荷：{plan.hours} 小时</h2><p>建议周一至周五各2小时，周末完成实训工单、10题周测和错题回炉。</p></div><label className="hours-control">每周可投入小时数<input type="number" min="8" max="24" value={hours} onChange={e=>setHours(Number(e.target.value))} onBlur={()=>setHours(plan.hours)}/><span>8—24小时</span></label></div><div className="phase-roadmap">{plan.phases.map((x,i)=><article key={x.name}><span>0{i+1}</span><div><p className="eyebrow">约 {x.hours} 小时</p><h2>{x.name}</h2><p>{x.goal}</p></div><button className="secondary" onClick={()=>go(i===3?'模拟考场':'章节精讲')}>进入阶段 <ArrowRight size={15}/></button></article>)}</div><div className="section-heading"><h2>20周训练周历</h2><span>默认12小时／周；每周都设置补训触发器</span></div><div className="week-table">{intensiveWeeks.map(x=><article key={x[0]}><strong>{x[0]}</strong><div><b>{x[1]}</b><p>本周交付：{x[2]}</p></div><span>{x[3]}</span></article>)}</div><div className="action-row"><button className="primary" onClick={()=>download('标途-20周计划.md',intensiveWeeks.map(x=>'## '+x[0]+'\n重点：'+x[1]+'\n交付：'+x[2]+'\n门槛：'+x[3]).join('\n\n'))}><Download size={16}/> 导出训练计划</button><a href="/implementation-plan.md" download>下载系统建设规划 <ArrowUpRight size={15}/></a></div></>}
 {view==='模拟考场'&&!lesson&&<><Heading tag="SIMULATED EXAMINATION" title="不是漂亮作业，是限时扛住项目。" body="全部情景为教学模拟。目标是检验事实判断、资料定位、交付质量和异常处置。" stamp="双线综合压测 · 5关"/><div className="exam-rules"><ShieldCheck size={23}/><div><h2>考场规则</h2><p>先列事实和缺口，再写结论；每项规则写来源；不得编造材料、审批或他人行为。</p></div></div><div className="studio-grid">{capstoneTasks.map(x=><article className="studio-card exam-card" key={x.id}><span className="type-label">限时考核</span><h2>{x.title}</h2><p>{x.hint}</p><div className="rubric"><b>老师按什么评分</b><p>{x.rubric}</p></div><label htmlFor={'exam-'+x.id}>我的答卷草稿</label><textarea id={'exam-'+x.id} rows={9} value={examDraft[x.id]||''} onChange={e=>{setExamDraft({...examDraft,[x.id]:e.target.value});setExamMessage('');}} placeholder="写事实、依据、判断、责任人、时间和证据……"/></article>)}</div><div className="review-panel"><div><h2>评分与淘汰规则</h2><p>建议标准：事实与来源25分，文件交付35分，节点与异常25分，留痕复盘15分。真实性、程序、签章、递交红线不以总分抵消。</p></div><div className="action-row"><button className="secondary" onClick={()=>{const missing=capstoneTasks.filter(x=>!(examDraft[x.id]||'').trim());setExamMessage(missing.length?'尚有'+missing.length+'关未填写：'+missing.map(x=>x.title).join('、'):'五关均已填写。质量与真实性由导师复核。');}}>检查完整性</button><button className="primary" onClick={()=>download('标途-综合压测答卷.md',report)}><Download size={16}/> 导出交导师</button></div>{examMessage?<p className="feedback">{examMessage}</p>:null}</div></>}
 {view==='资料库'&&!lesson&&<><Heading tag="RESEARCHED KNOWLEDGE BASE" title="先看权威依据，再看范本和案例。" body="课程骨架来自官方发布机关。地方范本、历史项目、学习笔记用于解释和练习，不能取代当期有效规则。" stamp={sourceBank.length+'项权威来源 · '+sources.materials.length+'份本地材料'}/><div className="research-note"><FileSearch size={22}/><p>每个重点卡显示应回查的本章来源。资料库保留发布机关原文、本地范本与案例、宿州抓取目录，便于从讲义回到文件核对。</p></div><div className="library-toolbar"><Tabs value={libraryTab} onValueChange={v=>setLibraryTab(String(v))}><TabsList className="path-tabs training-tabs"><TabsTrigger value="official">官方依据</TabsTrigger><TabsTrigger value="local">本地范本与案例</TabsTrigger><TabsTrigger value="portal">宿州抓取目录</TabsTrigger></TabsList></Tabs><label className="search-box"><Search size={17}/><input aria-label="搜索资料" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索标题、机关或主题…"/></label></div>{libraryTab==='official'?<div className="materials-grid">{sourceBank.filter(x=>(x.title+x.authority+x.note).includes(query.trim())).map(x=><article className="material-card official-card" key={x.id}><span className="type-label">{x.authority}</span><h3>{x.title}</h3><p>{x.note}</p><a href={x.url} target="_blank" rel="noreferrer">打开官方来源 <ExternalLink size={15}/></a></article>)}</div>:null}{libraryTab==='local'?<div className="materials-grid">{sources.materials.filter(x=>(x.title+x.kind+x.note).includes(query.trim())).map(x=><article className="material-card" key={x.id}><span className="type-label">{x.kind}</span><h3>{x.title}</h3><p>{x.note}</p><div className="material-footer"><small>{x.status}</small><a href={x.url} target="_blank" rel="noreferrer">打开原件 <ArrowUpRight size={15}/></a></div></article>)}</div>:null}{libraryTab==='portal'?<><div className="notice"><AlertCircle size={19}/><p>宿州国家政策法规栏目已抓取40条索引，其中35页取得较长文本、5页仍需从附件或外链补取正文。抓取成功不等于现行有效；正式题库以官方依据和专业审核为准。</p></div><div className="policy-list">{sources.policies.filter(x=>x.title.includes(query.trim())).map(x=><article className="policy-row" key={x.url}><div><h3>{x.title}</h3><p>{x.note}</p><small>{x.status}</small></div><a href={x.url} target="_blank" rel="noreferrer">宿州来源 <ExternalLink size={15}/></a></article>)}</div></>:null}</>}
 {view==='法规资料库'&&!lesson&&<RegulationLibrary query={query} tab={libraryTab} setTab={setLibraryTab}/>} 
 </main></div></SidebarProvider>;
}
